### PR TITLE
(RE-7420) Add sles mocks for use with foss packages

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by melissa** [comment]
The interesting thing is that some rpm-builder systems do have pl-sles mocks, but not all of them. I assume at some point there was code in this repo to add the sles mocks, but was removed. I didn't dig very deeply to figure that out, but that might not be a bad idea...

**Comment by melissa** [comment]
@shrug I think this is all we need. Is there anything else we might be missing?

**Comment by shrug** [comment]
I think that's it 👍

**Comment by melissa** [comment]
Also, @underscorgan since you have dealt with sles mocks before

**Comment by underscorgan** [comment]
I know there were weird things with sles mocks. I think @stahnma an @haus built them by hand last time.

**Pull request merged**
